-- ====================================================================
-- SQL Portfolio Project: Sales Data Analysis & Window Functions
-- Author: [Your Name]
-- Database: MySQL 8.0+
-- Description: Practice queries covering data type conversions, 
--              aggregations, CTEs, and window functions (LAG, DENSE_RANK).
-- ====================================================================

-- 1. Sample Data Inspection
SELECT *
FROM sales_data_practice;

-- --------------------------------------------------------------------
-- 1. Data Cleaning & Date Type Setup
-- --------------------------------------------------------------------
UPDATE sales_data_practice
SET sale_date = STR_TO_DATE(sale_date, '%Y-%m-%d');

ALTER TABLE sales_data_practice
MODIFY COLUMN sale_date DATE;

DESCRIBE sales_data_practice;

-- --------------------------------------------------------------------
-- 2. Top Performing Categories
-- Find the total revenue generated by each product category.
-- --------------------------------------------------------------------
SELECT 
    category, 
    ROUND(SUM(revenue), 2) AS total_revenue
FROM sales_data_practice
GROUP BY category 
ORDER BY total_revenue DESC;

-- --------------------------------------------------------------------
-- 3. Monthly Revenue Summary
-- Display total monthly revenue for the year formatted as YYYY-MM.
-- --------------------------------------------------------------------
SELECT 
    DATE_FORMAT(sale_date, '%Y-%m') AS y_month, 
    ROUND(SUM(revenue), 2) AS total_revenue
FROM sales_data_practice
GROUP BY y_month
ORDER BY y_month ASC;

-- --------------------------------------------------------------------
-- 4. Month-over-Month Revenue Difference
-- Display each month's revenue alongside the previous month's revenue and difference.
-- --------------------------------------------------------------------
WITH revenue_table AS (
    SELECT 
        DATE_FORMAT(sale_date, '%Y-%m') AS y_month,
        ROUND(SUM(revenue), 2) AS total_revenue
    FROM sales_data_practice
    GROUP BY y_month
    ORDER BY y_month ASC
)
SELECT 
    y_month,
    total_revenue,
    LAG(total_revenue, 1) OVER (ORDER BY y_month) AS previous_month,
    ROUND(total_revenue - LAG(total_revenue, 1) OVER (ORDER BY y_month), 2) AS monthly_growth
FROM revenue_table;

-- --------------------------------------------------------------------
-- 5. Category-Specific Difference
-- Compare the revenue of the current month with the previous month within each category.
-- --------------------------------------------------------------------
WITH cal_month_revenue AS (
    SELECT 
        category,
        DATE_FORMAT(sale_date, '%Y-%m') AS sales_month, 
        ROUND(SUM(revenue), 2) AS total_revenue
    FROM sales_data_practice
    GROUP BY category, sales_month
)
SELECT 
    category,
    sales_month,
    total_revenue,
    ROUND(LAG(total_revenue, 1, 0) OVER (PARTITION BY category ORDER BY sales_month), 2) AS previous_month,
    ROUND(total_revenue - LAG(total_revenue, 1, 0) OVER (PARTITION BY category ORDER BY sales_month), 2) AS monthly_diff
FROM cal_month_revenue;

-- --------------------------------------------------------------------
-- 6. Month-over-Month (MoM) Growth Percentage
-- Calculate the percentage growth in total revenue month-over-month.
-- --------------------------------------------------------------------
WITH revenue_table AS (
    SELECT 
        DATE_FORMAT(sale_date, '%Y-%m') AS y_month,
        SUM(revenue) AS total_revenue
    FROM sales_data_practice
    GROUP BY y_month
    ORDER BY y_month ASC
)
SELECT 
    y_month,
    total_revenue,
    LAG(total_revenue, 1) OVER (ORDER BY y_month) AS previous_month,
    ROUND(
        (total_revenue - LAG(total_revenue, 1) OVER (ORDER BY y_month)) 
        / LAG(total_revenue, 1) OVER (ORDER BY y_month) * 100, 
        2
    ) AS mom_growth_percent
FROM revenue_table;

-- --------------------------------------------------------------------
-- 7. Days Between Consecutive Sales per Region
-- Calculate days elapsed between consecutive sales within each region.
-- --------------------------------------------------------------------
SELECT 
    sale_date,
    region,
    LAG(sale_date, 1) OVER (PARTITION BY region ORDER BY sale_date) AS previous_date,
    DATEDIFF(sale_date, LAG(sale_date, 1) OVER (PARTITION BY region ORDER BY sale_date)) AS days_count
FROM sales_data_practice;

-- --------------------------------------------------------------------
-- 8. Top 2 Sales per Region
-- Find the top 2 highest-revenue sales transactions in each region.
-- --------------------------------------------------------------------
WITH ranked_revenue AS (
    SELECT 
        *,
        DENSE_RANK() OVER (PARTITION BY region ORDER BY revenue DESC) AS revenue_rank
    FROM sales_data_practice
)
SELECT *
FROM ranked_revenue
WHERE revenue_rank <= 2;
